[package]
name = "task_1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "1.2.0"
[dependencies.mongodb]
version = "2.0.2"
features = ["sync"]
